# @Author: Zackary BEAUGELIN <gysco>
# @Date:   2017-06-10T11:07:43+02:00
# @Email:  zackary.beaugelin@epitech.eu
# @Project: SSWD
# @Filename: .travis.yml
# @Last modified by:   gysco
# @Last modified time: 2017-06-10T11:09:14+02:00

language: python
python:
  - "3.5"
cache: pip
# command to install dependencies
addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev
install:
  - "pip install -r requirements.txt"
# command to run tests
script: pyinstaller -F pyment/__main__.py -n PyMENT-SSWD -w
