# @Author: Zackary BEAUGELIN <gysco>
# @Date:   2017-06-14T10:15:17+02:00
# @Email:  zackary.b@live.fr
# @Project: PyMENT-SSWD
# @Filename: .travis.yml
# @Last modified by:   gysco
# @Last modified time: 2017-06-20T13:57:32+02:00

language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.5
    env: TOXENV=py35
  - os: osx
    language: generic
    env: TOXENV=py35
cache: pip
install:
  - "./.travis/install.sh"
deploy:
  provider: releases
  api_key:
    secure: OiCT1LDzehrvva6oEI03LWuF+JLZr6s9uO93dRNb4rG4HxPngXklvnUpWjmDxuM4Q+qh0ZudRRP6RftL7M+Xb5YBs2QFDaYSA9Cqu5gFmZK1so9FStohFIjAIpHOinvbDJV2SFH7G+lU2KTZML0k4rz9dCclppIo/HCuxEKM48sn6vut1qo4G5FwdUdU7RRio8FzE30XHJkmJnvz6wT/mM5/RDIT4KfkGGgn3a7adtyzp4dNNwleRHk7wt+iycGALQwZ/qt26aqVV6/yn705sANzb5qmeQKFiyMxm0nNFmJoFcG7frXTR296L3y5qCNEhDDbh03qprvqc7LLHlXanSISel4595t6mzeA56o1WVg/Svwt3ZMmGwnVR0yDdypUaiR/LwR6cRgr/KXLqITcan18SJDcZ0S6NEaZorm9BHNl4WsZE1gKUmx0p0qfwelTPBrl9gCBewoFxpL/B+MfkhY74KJGRfDMX/SFMbXL7IL/WPjr1TZyBzbQLwvDJskPaU4M3+LXE15UgoB/wwNqthvBijKwlzFMnpo9fyCP9qu0qqTGYxVR4f0e2pJq2YS3xecGet5dm1w17ONtZ3g5FUP/XVr5QCkM14QJa0OkKXaZKczUmiCN6CgETxoLMURSgu4VP7M4b5xrVAKxL7QwqwyD27t4fErtUc4ZiTAuP1c=
  file:
    - "./dist/pyment-sswd_mac.dmg"
    - "./dist/pyment-sswd_mac.zip"
    - "./dist/pyment-sswd_unix.tar.gz"

  skip_cleanup: true
  on:
    tags: true
