#!/usr/bin/env python3
"""
File to execute SSWD.

Parse commande line and csv file.
"""

# @Author: Zackary BEAUGELIN <gysco>
# @Date:   2017-04-27T09:39:06+02:00
# @Email:  zackary.beaugelin@epitech.eu
# @Project: SSWD
# @Filename: run.py
# @Last modified by:   gysco
# @Last modified time: 2017-05-23T11:03:44+02:00

import argparse
import sys
from os.path import splitext

import pandas

from Fct_ihm import charger_parametres


def isp_type(x):
    """Check isp type."""
    x = str(x)
    to_index = ["w", "u", "m"]
    if x not in to_index:
        raise argparse.ArgumentTypeError(
            "%s has to be: m(ean)/w(eighted)/u(nweighted) for ponderation" %
            (x, ))
    return (to_index.index(x))


def restricted_float(x):
    """Check float hazen."""
    x = float(x)
    if x < 0.0 or x > 1.0:
        raise argparse.ArgumentTypeError("%r not in range [0.0, 1.0]" % (x, ))
    return x


def parse_file(filename, colnames):
    """Parse file using pandas module."""
    if not filename:
        raise argparse.ArgumentTypeError("Filename (-f) is None.")
    if splitext(filename)[1] in ['.xls', '.xlsx']:
        data = pandas.read_excel(filename, sheetname=None)
        # select sheetname
        data = data['chronic']
    elif splitext(filename)[1] is '.csv':
        data = pandas.read_csv(filename, header=0)
        if len(data.columns) == 1:
            data = pandas.read_csv(filename, sep=";", header=0)
    else:
        raise IOError("Invalid file")
    espece = filename + "!"
    test = filename + "!"
    for n in data[colnames[0]].tolist():
        espece += str(n) + ";"
        test += str(n) + ";"
    taxo = filename + "!"
    for n in data[colnames[1]].tolist():
        taxo += str(n) + ";"
    concentration = filename + "!"
    for n in data[colnames[2]].tolist():
        concentration += str(n) + ";"
    return (espece, taxo, concentration, test)


def get_columns(filename):
    """Get columns for further parsing."""
    names = list()
    if not filename:
        raise argparse.ArgumentTypeError("Filename (-f) is None.")
    data = pandas.read_csv(filename, header=0)
    if len(data.columns) == 1:
        data = pandas.read_csv(filename, sep=";", header=0)
    for x in data.columns:
        names.append(str(x))
    return (names)


def main():
    """Main."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--save", help="Save intermediate operations", action="store_true")
    parser.add_argument(
        "--emp", help="Enable empirical law", action="store_true")
    parser.add_argument(
        "--normal", help="Enable normal law", action="store_true")
    parser.add_argument(
        "--triang", help="Enable triangular law", action="store_true")
    parser.add_argument("--iproc", help="iproc value", default=1, type=int)
    parser.add_argument(
        "--hazen", help="Hazen parameter a", default=.5, type=restricted_float)
    parser.add_argument("-f", "--file", help="filename")
    parser.add_argument("--pcat", help="pcat values or colonne", type=str)
    parser.add_argument(
        "--bootstrap", help="bootstrap n times", default=1000, type=int)
    parser.add_argument("--nbvar", help="enable nbvar", action="store_true")
    parser.add_argument(
        "--adjustq", help="adjust q for triangular law", action="store_true")
    parser.add_argument(
        "--isp", help="poderation type", default=1, type=isp_type)
    parser.add_argument("--lbl_liste", help="weight of each taxonomic group")
    args = parser.parse_args()
    # columns_name = get_columns(args.file)
    columns_name = ["Species", "PhylumSup", "ED"]
    espece, taxo, concentration, test = parse_file(args.file, columns_name)
    charger_parametres(
        args.file, args.iproc, espece, taxo, concentration, test, args.pcat,
        args.pcat is None, args.pcat is not None, args.emp, args.normal,
        args.triang, args.bootstrap, args.hazen, args.nbvar, args.save,
        args.lbl_liste, args.triang and args.adjustq, args.isp, columns_name)
    return (0)


if __name__ == '__main__':
    sys.exit(main())
