#!/usr/bin/env python3
# coding=utf-8

# @Author: Zackary BEAUGELIN <gysco>
# @Date:   2017-05-29T11:42:22+02:00
# @Email:  zackary.beaugelin@epitech.eu
# @Project: SSWD
# @Filename: test
# @Last modified by:   gysco
# @Last modified time: 2017-06-01T11:41:41+02:00
"""Test file."""

import multiprocessing

if __name__ == '__main__':
    print(multiprocessing.cpu_count())
